### ISSUE TITLE
docs: warn against changing documents that are synced from upstream repos

### ISSUE THREAD

**Issue by carlaKC** [lightninglabs/docs.lightning.engineering#35]
first (issue)!

Once #34 is merged, we will have documents from various LL repos pulled in to `docs/{repo name}` with an hourly sync. If changes are made to those synced documents by people looking to contribute to the docs dir, they will be overwritten by the sync. Changes should instead be made to the upstream repo, and then the sync will take care of the rest.

This isn't the _best_ contributor flow, but is a consequence of our decision to leave docs in their upstream repos. Some documentation around this would be useful to prevent headaches for the kind souls who take the time to help us improve our docs.

**Comment by guggero** [comment]
Definitely. I think medium term we can add a GitHub action that checks what docs are modified (and skips PRs created by the sync action). Maybe for now adding a PR checklist that mentions which directories not to change would be enough?
